#### Numpy
 * n차원 배열의 객체
 * 이산수학과 무작위 수 생성 등 수많은 작업을 할 수 있는기능이 제공됨
 * 벡터와 행렬을 위한 특수한 배열 형식을 제공
 * 생성될 때 크기가 정해짐
 * 텐서플로우와 잘 어울림

###### zeros() & mean()

In [10]:
import numpy as np 


#인자로 전달받은 숫자만큼 0인 원소를 생성
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])
z = np.zeros(10)
w = np.zeros([3,4])
print(w)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
x = x*5
x

array([ 5, 10, 15, 20])

In [12]:
z = z +10
z

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [13]:
type([ 5, 10, 15, 20])
x = [ 5, 10, 15, 20]

list

In [14]:
arr = np.array(x)
print(arr.mean())

12.5


In [15]:
# 배열의 속성을 알수 있다.
arr.shape

(4,)

###### reshape

In [17]:
x = range(1, 11)
arr = np.array(x)
arr.shape

(10,)

In [21]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

###### ones()

In [29]:
x = np.ones(12)


In [30]:
x = x*5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [33]:
x.reshape(2,3,2)

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

#### numpy 배열의 슬라이싱

In [36]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(3,4)
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
# y의 모든행의 2열 원소들만 추출
y[: , 1]

array([ 2,  6, 10])

In [38]:
# 2~3행까지의 3열의 원소믈만 추출
y[1:, 2]

array([ 7, 11])

In [39]:
#2행의 모든열
y[1,:]

array([5, 6, 7, 8])

In [43]:
import math
math.sqrt(16)

TypeError: must be real number, not list

In [42]:
np.sqrt(16)

4.0

In [44]:
np.sqrt([1,9, 16])

array([1., 3., 4.])

##### 전치행렬  transpose()

In [54]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape(2,6)
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [56]:
y = y.transpose()
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

##### 배열의 연산

In [67]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = x.reshape(2,6)
z = y*4
z

array([[ 4,  8, 12, 16, 20, 24],
       [28, 32, 36, 40, 44, 48]])

In [68]:
np.log10(y)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
        0.77815125],
       [0.84509804, 0.90308999, 0.95424251, 1.        , 1.04139269,
        1.07918125]])

In [70]:
y , z

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[ 4,  8, 12, 16, 20, 24],
        [28, 32, 36, 40, 44, 48]]))

In [71]:
y[:, 2] * z[:, 3]

array([ 48, 360])

##### bool형 리턴

In [72]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = x.reshape(2,6)
y>5

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True]])

■ **Table of Contents**

- [random.rand()](https://codetorial.net/numpy/random.html#random-rand)
- [random.randint()](https://codetorial.net/numpy/random.html#random-randint)
- [random.randn()](https://codetorial.net/numpy/random.html#random-randn)
- [random.standard_normal()](https://codetorial.net/numpy/random.html#random-standard-normal)
- [random.normal()](https://codetorial.net/numpy/random.html#random-normal)
- [random.random_sample()](https://codetorial.net/numpy/random.html#random-random-sample)
- [random.choice()](https://codetorial.net/numpy/random.html#random-choice)
- [random.seed()](https://codetorial.net/numpy/random.html#random-seed)



##### random.rand()

In [249]:
import numpy as np

a = np.random.rand(5)
print(a)

b = np.random.rand(2, 3)
print(b)

[0.0515055  0.25150815 0.72591016 0.75542853 0.2133876 ]
[[0.14370758 0.43890596 0.66173262]
 [0.77481787 0.59959906 0.77451236]]


##### random.randint()

np.random.randint(2, size=5)는 [0, 2) 범위에서 다섯개의 임의의 정수를 생성합니다.

np.random.randint(2, 4, size=5)는 [2, 4) 범위에서 다섯개의 임의의 정수를 생성합니다.

np.random.randint(1, 5, size=(2, 3))는 [1, 5) 범위에서 (2, 3) 형태의 어레이를 생성합니다.

In [146]:
import numpy as np

a = np.random.randint(4, size=5)
print(a)

b = np.random.randint(2, 5, size=5)
print(b)

c = np.random.randint(1, 5, size=(2, 3))
print(c)

[2 0 1 2 2]
[3 4 3 3 4]
[[2 1 2]
 [2 3 4]]


##### random.randn()

random.randn() 함수는 표준정규분포 (Standard normal distribution)로부터 샘플링된 난수를 반환합니다.

In [181]:
import numpy as np

a = np.random.randn(5)
print(a)
print(type(a))
b = np.random.randn(2, 3)
print(b)

sigma, mu = 1.5, 2.0

c = sigma * np.random.randn(5) + mu
print(c)

[1.00994458 0.83256795 1.22549515 0.82728987 1.19874172]
<class 'numpy.ndarray'>
[[ 1.33512052  0.20447797  0.47278947]
 [-0.74343754 -1.13339117  1.68898971]]
[2.8654701  1.37395015 2.24466265 2.54740633 3.10425272]


##### random.standard_normal()

In [182]:
import numpy as np

d = np.random.standard_normal(3)
print(d)

e = np.random.standard_normal((2, 3))
print(e)

[ 1.05381643 -1.95463516 -2.32767366]
[[ 0.9288438  -0.20449563  1.33387874]
 [-0.05606061  0.89398092  0.07562618]]


###### random.normal()
어레이 a는 정규 분포 N(0,1)로부터 얻은 임의의 숫자 2개,

어레이 b는 정규 분포 N(1.5,1.52)로부터 얻은 임의의 숫자 4개,

어레이 c는 정규 분포 N(3.0,2.02)로부터 얻은 (2, 3) 형태의 임의의 숫자 어레이입니다.

In [225]:
import numpy as np

a = np.random.normal(0, 1, 2)
print(a)

b = np.random.normal(1.5, 1.5, 4)
print(b)

c = np.random.normal(3.0, 2.0, (2, 3))
print(c)

[-0.31736309 -0.95194759]
[1.64452255 2.75302848 0.94287414 2.97960677]
[[ 7.10860944  2.97615612 -0.53455631]
 [ 1.00802944  2.77862644  4.67502001]]


##### random.seed()

In [274]:
import numpy as np

np.random.seed(0)

print(np.random.rand(2, 3))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]


#### ▪ linspace()
시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분

In [278]:
np.linspace(0,12,11)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8, 12. ])

In [282]:
np.linspace(0,12,10 , retstep=True)

(array([ 0.        ,  1.33333333,  2.66666667,  4.        ,  5.33333333,
         6.66666667,  8.        ,  9.33333333, 10.66666667, 12.        ]),
 1.3333333333333333)

In [292]:
np.linspace(0,12,10 , retstep=True , endpoint=False)

array([ 0. ,  1.2,  2.4,  3.6,  4.8,  6. ,  7.2,  8.4,  9.6, 10.8])

#### logspace()

In [289]:
np.logspace(1, 2 , 5 ,endpoint=False)

array([10.        , 15.84893192, 25.11886432, 39.81071706, 63.09573445])